### ISSUE TITLE
Add logging with timeline_id that operation failed in some pageserver http handler

### ISSUE THREAD

**Issue by ololobus** [neondatabase/neon#2419]
There was a project on staging from September 7 created by periodic load https://console.stage.neon.tech/admin/operations?project_id=rough-queen-354759

Operation `create_timeline` failed on first attempt with error `pageserver responded with status 500`, but there were not any related errors in the pageserver log for this timeline during this interval https://observer.zenith.tech/d/8jHyEQOnz/zenith-logs-pageserver?orgId=1&var-environment=staging&var-instance=zenith-us-stage-ps-3.local&var-search=caf8609024a1104786c2ea7ea5e2b2b1&var-exclude=substing%20to%20exclude&from=1662558329375&to=1662558720139

Dmitry Rodionov pointed me to the error with trace [https://observer.zenith.tech/d/8jHyEQOnz/zenith-logs-pageserver?orgId=1&var-environment[…]&var-exclude=gc%20loop&from=1662558329375&to=1662558720139](https://observer.zenith.tech/d/8jHyEQOnz/zenith-logs-pageserver?orgId=1&var-environment=staging&var-instance=zenith-us-stage-ps-3.local&var-search=ERROR%20Error%20processing%20HTTP%20request&var-exclude=gc%20loop&from=1662558329375&to=1662558720139)

But it doesn't contain `timeline_id`, which makes searching for errors more complicated.

Let's either somehow propagate `timeline_id` to http server (which looks a bit as an abstraction leaking) or log about operation failure before that in the pageserver code. Or there are better ideas?

**Comment by sharnoff** [comment]
Closing after discussion with @﻿hlinnaka - this should already be fixed:

While `ApiError::into_response` doesn't log anything...

https://github.com/neondatabase/neon/blob/687ba81366491c84250e4df9c20e31e595b34476/libs/utils/src/http/error.rs#L27-L49

... **but!** the only place it's called is in the nearby `handler` function, which always does:

https://github.com/neondatabase/neon/blob/687ba81366491c84250e4df9c20e31e595b34476/libs/utils/src/http/error.rs#L78-L83

For completion, `handler` is only used when it's attached as the error handler for the router:

https://github.com/neondatabase/neon/blob/687ba81366491c84250e4df9c20e31e595b34476/libs/utils/src/http/endpoint.rs#L57-L62

**Comment by ololobus** [comment]
> but! the only place it's called is in the nearby handler function, which always does:

@sharnoff, can you please elaborate a bit? In the cited piece of code I see only that blank error is logged, neither tenant / timeline, nor http endpoint are mentioned. So I'm still not sure how to find the error by searching with tenant / timeline id

**Comment by sharnoff** [comment]
@ololobus Actually, I think I misread your issue - when you say:

> Operation `create_timeline` failed on first attempt with error `pageserver responded with status 500`, but **there were not any related errors in the pageserver log for this timeline during this interval**
>
> [ ... ]
>
> Dmitry Rodionov **pointed me to the error with trace** [ ... ] **But it doesn't contain `timeline_id`**, which makes searching for errors more complicated

... do you mean that there are errors, but the `TimelineId` is not present in them? If so, then I incorrectly closed your issue; AFAIK that is not already resolved.

**Comment by ololobus** [comment]
> do you mean that there are errors in the pageserver's log, but the TimelineId is not present in them? If so, then I incorrectly closed your issue; AFAIK that is not already resolved.

Yeah, the problem was that:
- you go to the console, see that some timeline / tenant creation with error failed with aforementioned error
- you copy the timeline or tenant id
- go to grafana and search pageserver logs with this id
- and you see only some info records that pageserver was serving some requests for this tenant / timeline, but no errors
- to get the actual error you need to figure out error time frame, opens **all** logs within it, and look for traces nearby the info record

What would be nice is to see errors like:
```
ERROR: request POST /v1/tenant for tenant xxxxxx failed with: {error}
```

**Comment by ololobus** [comment]
> Would prefixing the full route used work?

It would work, but for example, for tenant creation I mentioned we have only `/v1/tenant` in path and tenant id is passed as request body

**Comment by sharnoff** [comment]
Ok I see, that's unfortunate. I'll see if there's semi-reasonable middleware-based way of doing this (printing both route & body)

**Comment by ololobus** [comment]
> semi-reasonable middleware-based way of doing this (printing both route & body)

Yeah, also thought about it

**Comment by shanyp** [comment]
@sharnoff we log the request-id in the entering and leaving of the http calls, so breadcrumbs are there 
@koivunej as FYI

**Comment by jcsp** [comment]
We're in pretty good shape for including timeline_ids in trace span these days -- the create_timeline case mentioned in this ticket at least is certainly fixed.
